site_name: Pundah.Org
site_url: https://sitename.example
repo_name: pundah.org
repo_url: https://github.com/Pundah/pundah.org
edit_uri: blob/main/docs/
use_directory_urls: true
theme:
#  custom_dir: overrides
  name: material
  highlightjs: true
  language: en
  prev_next_buttons_location: none
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/My Logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - announce.dismiss
    - content.action.edit
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - toc.follow
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: green
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: amber
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: simple/discord
      link: https://discord.pundah.org
  generator: false
  homepage: /
  version:
    default: stable
copyright: Copyright &copy; 2025 Pundah.org
plugins:
  - search
  - awesome-pages: {
    collapse_single_pages: true,
    strict: true,
  }
  - meta-descriptions
  - tags
  - mkdocs-video
  - markmap
#  - blog
#  - autoref
  - git-revision-date-localized: {
    type: timeago,
    enable_creation_date: true,
    fallback_to_build_date: false,
    strict: !ENV [ENABLE_STRICT_GIT_REVISION_DATE, false],
    enabled: !ENV [ENABLE_GIT_REVISION_DATE, false]
  }
  - minify: {
    minify_html: !ENV [ENABLE_MINIFY, false],
    minify_js: !ENV [ENABLE_MINIFY, false],
    minify_css: !ENV [ENABLE_MINIFY, false],
    htmlmin_opts: {
      remove_comments: !ENV [ENABLE_REMOVE_COMMENTS, false]
    },
    cache_safe: true
  } 
#  - offline: {
#    enabled: !ENV [ENABLE_OFFLINE, false]
#  }
  - glightbox: {
    touchNavigation: true,
    loop: true,
    effect: fade,
    slide_effect: fade,
    width: auto,
    height: auto,
    draggable: false,
    auto_caption: true,
    caption_position: bottom
  }
  - git-authors: {
    show_email_address: false,
    sort_authors_by: contribution,
    fallback_to_empty: true,
    show_contribution: true,
    strict: !ENV [ENABLE_STRICT_GIT_AUTHORS, false],
    enabled: !ENV [ENABLE_GIT_AUTHORS, false]
  }
validation:
  nav:
    omitted_files: info
    not_found: info
    absolute_links: info
  links:
    not_found: info
    absolute_links: info
    unrecognized_links: info